
INSERT INTO MuscleGroup (name)
VALUES ('Chest'), ('Back'), ('Legs'), ('Biceps'), ('Shoulders'), ('Abs'), ('Triceps'), ('Forearms');

INSERT INTO Exercise (name, description, difficulty_level, type, muscle_group_id)
VALUES 
    ('Bench Press', 'Targets the chest', 'Intermediate', 'Push', 1),
    ('Pull-Up', 'Targets the back', 'Advanced', 'Pull', 2),
    ('Squat', 'Targets the legs', 'Intermediate', 'Other', 3),
    ('Bicep Curl', 'Targets the biceps', 'Beginner', 'Pull', 4),
    ('Shoulder Press', 'Targets the shoulders', 'Intermediate', 'Push', 5),
    ('Crunches', 'Targets the abs', 'Beginner', 'Other', 6),
    ('Deadlift', 'Targets the lower back and hamstrings', 'Advanced', 'Pull', 2),
    ('Push-Up', 'Works chest, shoulders, and triceps', 'Beginner', 'Push', 1),
    ('Leg Press', 'Targets the quadriceps and glutes', 'Intermediate', 'Push', 3),
    ('Lat Pulldown', 'Targets the latissimus dorsi', 'Intermediate', 'Pull', 2),
    ('Tricep Extension', 'Isolates the triceps', 'Beginner', 'Push', 7),
    ('Lunges', 'Targets quads, hamstrings, and glutes', 'Intermediate', 'Other', 3),
    ('Bicycle Crunch', 'Targets the abs and obliques', 'Beginner', 'Other', 6),
    ('Hammer Curl', 'Targets the brachialis and biceps', 'Beginner', 'Pull', 4),
    ('Chest Fly', 'Targets the chest', 'Intermediate', 'Push', 1),
    ('Seated Row', 'Targets the upper back', 'Intermediate', 'Pull', 2),
    ('Leg Curl', 'Isolates the hamstrings', 'Intermediate', 'Pull', 3),
    ('Plank', 'Targets core stability', 'Beginner', 'Other', 6),
    ('Overhead Tricep Extension', 'Targets triceps', 'Intermediate', 'Push', 7),
    ('Front Squat', 'Focuses on quads', 'Advanced', 'Other', 3),
    ('Incline Bench Press', 'Upper chest emphasis', 'Intermediate', 'Push', 1),
    ('Bent Over Row', 'Targets back and biceps', 'Intermediate', 'Pull', 2),
    ('Calf Raise', 'Isolates the calves', 'Beginner', 'Other', 3),
    ('Russian Twist', 'Works abs and obliques', 'Intermediate', 'Other', 6),
    ('Face Pull', 'Rear deltoid and upper back', 'Intermediate', 'Pull', 5),
    ('Cable Fly', 'Chest isolation', 'Intermediate', 'Push', 1),
    ('T-Bar Row', 'Targets mid-back', 'Advanced', 'Pull', 2),
    ('Goblet Squat', 'Quads and glutes', 'Beginner', 'Other', 3),
    ('Dumbbell Shoulder Press', 'Shoulders and triceps', 'Intermediate', 'Push', 5),
    ('Hanging Leg Raise', 'Targets lower abs', 'Advanced', 'Other', 6),
    ('Bulgarian Split Squat', 'Targets quads, glutes, and improves balance', 'Intermediate', 'Other', 3),
    ('Dumbbell Pullover', 'Works chest and lats simultaneously', 'Intermediate', 'Push', 1),
    ('Renegade Row', 'Combines core stability and back strength', 'Advanced', 'Pull', 2),
    ('Arnold Press', 'A variation of shoulder press for full deltoid activation', 'Intermediate', 'Push', 5),
    ('Side Plank', 'Strengthens obliques and core stability', 'Beginner', 'Other', 6),
    ('Reverse Lunge', 'Emphasizes glutes and hamstrings', 'Beginner', 'Other', 3),
    ('Spider Curl', 'Targets the biceps peak with isolation', 'Intermediate', 'Pull', 4),
    ('Pec Deck Fly', 'Machine-based chest isolation', 'Beginner', 'Push', 1),
    ('Inverted Row', 'Bodyweight exercise for back and arms', 'Beginner', 'Pull', 2),
    ('Hip Thrust', 'Glute isolation for lower body power', 'Intermediate', 'Push', 3),
    ('Hanging Knee Raise', 'Focuses on lower abs and hip flexors', 'Intermediate', 'Other', 6),
    ('Farmer’s Carry', 'Improves grip, core, and shoulder stability', 'Intermediate', 'Other', 7),
    ('Wall Sit', 'Static leg exercise for endurance', 'Beginner', 'Other', 3),
    ('Landmine Press', 'Targets chest and shoulders with core stability', 'Intermediate', 'Push', 5),
    ('Pallof Press', 'Anti-rotation exercise for core stability', 'Intermediate', 'Push', 6),
    ('Good Morning', 'Strengthens lower back, glutes, and hamstrings', 'Advanced', 'Pull', 3),
    ('Landmine Row', 'Back exercise with single-arm variation for stability', 'Intermediate', 'Pull', 2),
    ('Zottman Curl', 'Combines bicep curl and reverse curl for forearms', 'Intermediate', 'Pull', 4),
    ('Mountain Climbers', 'Cardio and core exercise', 'Beginner', 'Other', 6),
    ('Box Jump', 'Plyometric exercise for explosive leg power', 'Intermediate', 'Other', 3),
    ('Barbell Reverse Wrist Curls', 'Strengthens the forearm muscles by focusing primarily on the forearm extensor muscles.', 'Beginner', 'Other', 8),
    ('Dumbell Wrist Curls', 'Strengthens the forearm muscles focusing on the forearm flexors.', 'Beginner', 'Other', 8),
    ('Reverse Barbell Curls', 'Strengthens the forearm muscles and targets the forearm extensor muscles.', 'Beginner', 'Other', 8),
    ('Reverse Wrist Curls', 'Strengthens the forearm muscles by pulling and rolling.', 'Beginner', 'Other', 8),
    ('Bar Hang', 'Bar Hangs build grip strength, forearm endurance, and shoulder stability.', 'Intermediate', 'Other', 8),
    ('Towel Pullups', 'Improves grip strength by doubling the amount of wokr your forearms do in a pullup.', 'Advanced', 'Other', 8);